import 'package:flutter/foundation.dart';

/// Role of a single message in the chat conversation.
enum ChatRole {
  /// Message sent by the app user.
  user,

  /// Message generated by the assistant.
  assistant,
}

/// A single chat message shown in the conversation history.
@immutable
class ChatMessage {
  final ChatRole role;
  final String text;

  /// Optional timestamp; null messages (e.g. the welcome message) hide it.
  final DateTime? timestamp;

  const ChatMessage({
    required this.role,
    required this.text,
    this.timestamp,
  });

  bool get isUser => role == ChatRole.user;

  /// Formats the timestamp as a 24-hour clock string, e.g. "14:05".
  /// Returns an empty string when the message has no timestamp.
  String get formattedTime {
    final time = timestamp;
    if (time == null) return '';
    final hours = time.hour.toString().padLeft(2, '0');
    final minutes = time.minute.toString().padLeft(2, '0');
    return '$hours:$minutes';
  }
}
